[build]
  command = "npx expo export -p web && cp public/sw.js dist/sw.js"
  publish = "dist"

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
