import assert from 'node:assert';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const source = readFileSync(fileURLToPath(new URL('./RichDescriptionEditor.tsx', import.meta.url).href), 'utf8');
assert.match(source, /focusTitle\?: string/);
assert.match(source, /sidebarMode\?: boolean/);
assert.match(source, /sidebarMode=false/);
assert.match(source, /useState<'edit'\|'preview'\|'split'>\('edit'\)/);
assert.match(source, /expandedWidth/);
assert.match(source, /const canSplit=expandedWidth>=900&&value\.trim\(\)\.length>0/);
assert.match(source, /onLayout=\{event=>setExpandedWidth\(event\.nativeEvent\.layout\.width\)\}/);
assert.match(source, /setMode\('split'\)/);
assert.match(source, /accessibilityLabel="split description"/);
assert.match(source, /mode==='split'/);
assert.match(source, /toolbar\(false,sidebarMode\)/);
assert.doesNotMatch(source, /sidebarMode\?<View/);
assert.match(source, /desktopBreakpoint=\{768\}/);
assert.match(source, /accessibilityState=\{\{selected:mode===tab\}\}/);
assert.match(source, /MAX_INPUT/);
assert.match(source, /!open&&<View/);
assert.match(source, /open&&<Popup/);
assert.match(source, /renderInput\(true\)/);
assert.match(source, /renderInput\(false\)/);
assert.match(source, /selection=\{selection\}/);
assert.match(source, /onDoubleClick/);
assert.match(source, /Show advanced formatting/);
assert.match(source, /Add table row/);
assert.match(source, /Remove table column/);
assert.match(source, /tableSelection/);
assert.match(source, /Increase table rows/);
assert.match(source, /Decrease table columns/);
assert.match(source, /Insert \$\{tableRows\} by \$\{tableColumns\} table/);
assert.match(source, /e\.key==='Escape'&&tableBuilder/);
assert.match(source, /if\(mode==='preview'\)setMode\('edit'\)/);
assert.doesNotMatch(source, /!desktop&&mode==='preview'/);
assert.doesNotMatch(source, /closeEditor=.*setTimeout\(\(\)=>inputRef\.current\?\.focus\(\),30\)/);
assert.doesNotMatch(source, /dangerouslySetInnerHTML|html:/i);
console.log('RichDescriptionEditor: static contract assertions passed');
