import FontAwesome from '@expo/vector-icons/FontAwesome';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, Text, TextInput, TouchableOpacity, useWindowDimensions, View } from 'react-native';
import Popup from './Popup';
import Tooltip from './Tooltip';
import MarkdownDescription from './MarkdownDescription';
import { useThemeColors } from '@/hooks/useThemeColors';
import { useScopedMarkdownFileIntake } from '@/hooks/useWebDnd';
import { pickMarkdownFile } from '@/lib/fileTransfer';
import { importMarkdownFile, MarkdownImportSuccess, mergeMarkdownAtSelection } from '@/lib/markdownFileImport';
import { applyMarkdownCommand, continueMarkdownOnEnter, MAX_BLOCKS, MAX_INPUT, MarkdownCommand, parseTaskDescriptionMarkdown } from '@/lib/taskDescriptionMarkdown';

type Props = { value: string; onChangeText: (value: string) => void; placeholder?: string; minHeight?: number; testID?: string; focusTitle?: string; sidebarMode?: boolean };
type Tool = { label: string; icon: string; command: MarkdownCommand };
const TOOLS: Tool[] = [
  { label:'Bold',icon:'B',command:'bold' }, { label:'Italic',icon:'I',command:'italic' }, { label:'Strike',icon:'S',command:'strike' },
  { label:'Heading',icon:'H',command:'heading' }, { label:'Bulleted list',icon:'•',command:'bullet' }, { label:'Numbered list',icon:'1.',command:'number' },
  { label:'Checklist',icon:'☑',command:'checklist' }, { label:'Quote',icon:'❯',command:'quote' }, { label:'Inline code',icon:'<>',command:'inlineCode' },
  { label:'Fenced code',icon:'{}',command:'codeBlock' }, { label:'Link',icon:'↗',command:'link' }, { label:'Divider',icon:'―',command:'divider' }, { label:'Table',icon:'▦',command:'table' },
];

export default function RichDescriptionEditor({ value, onChangeText, placeholder='Write a description…', minHeight=120, testID, focusTitle='Description', sidebarMode=false }: Props) {
  const colors=useThemeColors(); const inputRef=useRef<TextInput>(null); const {width}=useWindowDimensions();
  const [open,setOpen]=useState(false); const [mode,setMode]=useState<'edit'|'preview'|'split'>('edit'); const [expandedWidth,setExpandedWidth]=useState(0); const [advanced,setAdvanced]=useState(false); const [tableBuilder,setTableBuilder]=useState(false); const [tableRows,setTableRows]=useState(2); const [tableColumns,setTableColumns]=useState(2); const [selection,setSelection]=useState({start:value.length,end:value.length});
  const previewLimited=useMemo(()=>value.length>=MAX_INPUT||parseTaskDescriptionMarkdown(value).length>=MAX_BLOCKS,[value]);
  const canSplit=expandedWidth>=900&&value.trim().length>0;
  useEffect(()=>{if(mode==='split'&&!canSplit)setMode('edit');},[canSplit,mode]);
  const history=useRef<string[]>([]); const future=useRef<string[]>([]); const previous=useRef(value); const pendingInternal=useRef<string|null>(null);
  const [markdownImport, setMarkdownImport] = useState<MarkdownImportSuccess | null>(null);
  const [markdownNotice, setMarkdownNotice] = useState<{kind:'error'|'info';message:string} | null>(null);
  useEffect(()=>{ if(previous.current!==value){ const internal=pendingInternal.current===value; const equalLength=previous.current.length===value.length; previous.current=value; pendingInternal.current=null; if(!internal){ history.current=[]; future.current=[]; setSelection(equalLength?{start:value.length,end:value.length}:{start:Math.min(selection.start,value.length),end:Math.min(selection.end,value.length)}); } } },[value]);
  const change=(next:string)=>{ if(next===value)return; history.current=[...history.current.slice(-49),value]; future.current=[]; previous.current=next; pendingInternal.current=next; onChangeText(next); };
  const tableSelection=()=>{let start=value.lastIndexOf('\n',Math.max(0,selection.start-1))+1;let end=value.indexOf('\n',selection.end);if(end<0)end=value.length;const isTableLine=(at:number)=>{const lineEnd=value.indexOf('\n',at);return value.slice(at,lineEnd<0?value.length:lineEnd).includes('|');};if(!isTableLine(start)){start=value.indexOf('|');if(start<0)return null;start=value.lastIndexOf('\n',start-1)+1;end=value.indexOf('\n',start);if(end<0)end=value.length;}while(start>0){const previousEnd=start-1,previousStart=value.lastIndexOf('\n',previousEnd-1)+1;if(!isTableLine(previousStart))break;start=previousStart;}while(end<value.length){const nextStart=end+1;if(!isTableLine(nextStart))break;const nextEnd=value.indexOf('\n',nextStart);end=nextEnd<0?value.length:nextEnd;}return {start,end};};
  const insert=(command:MarkdownCommand)=>{if(command==='table'){setTableBuilder(current=>!current);return;}if(mode==='preview')setMode('edit');const r=applyMarkdownCommand(value,selection,command); change(r.value); setSelection(r.selection); setTimeout(()=>inputRef.current?.focus(),0);};
  const insertTable=()=>{if(mode==='preview')setMode('edit');const r=applyMarkdownCommand(value,selection,'table',{tableRows,tableColumns});change(r.value);setSelection(r.selection);setTableBuilder(false);setTimeout(()=>inputRef.current?.focus(),0);};
  const tableAction=(command:MarkdownCommand)=>{const range=tableSelection();if(!range)return;setSelection(range);const r=applyMarkdownCommand(value,range,command);change(r.value);setSelection(r.selection);setMode('edit');setTimeout(()=>inputRef.current?.focus(),0);};
  const undo=()=>{const prior=history.current.pop();if(prior===undefined)return;future.current.push(value);previous.current=prior;pendingInternal.current=prior;onChangeText(prior);setSelection({start:prior.length,end:prior.length});};
  const redo=()=>{const next=future.current.pop();if(next===undefined)return;history.current.push(value);previous.current=next;pendingInternal.current=next;onChangeText(next);setSelection({start:next.length,end:next.length});};
  const importReviewNotice=(result:MarkdownImportSuccess)=>result.unsupported.length?`Imported ${result.name}. Review unsupported constructs: ${result.unsupported.join(', ')}.`:null;
  const applyMarkdownImport=(source: string,notice?:string|null)=>{if(mode==='preview')setMode('edit');const r=mergeMarkdownAtSelection(value,selection,source);change(r.value);setSelection(r.selection);setMarkdownImport(null);setMarkdownNotice(notice?{kind:'info',message:notice}:null);setTimeout(()=>inputRef.current?.focus(),0);};
  const prepareMarkdownImport=(result:ReturnType<typeof importMarkdownFile>)=>{if(!result.ok){setMarkdownImport(null);setMarkdownNotice({kind:'error',message:result.message});return;}setMarkdownNotice(null);if(value.length===0)applyMarkdownImport(result.source,importReviewNotice(result));else setMarkdownImport(result);};
  const readMarkdownFile=async(file: {name: string; arrayBuffer:()=>Promise<ArrayBuffer>})=>{try { prepareMarkdownImport(importMarkdownFile(file.name,new Uint8Array(await file.arrayBuffer()))); } catch { setMarkdownImport(null);setMarkdownNotice({kind:'error',message:'The selected Markdown file could not be read.'}); }};
  const chooseMarkdownFile=async()=>{const picked=await pickMarkdownFile();if(picked)prepareMarkdownImport(importMarkdownFile(picked.name,picked.bytes));};
  const markdownIntake=useScopedMarkdownFileIntake(readMarkdownFile as (file: File)=>void, open);
  const openEditor=()=>{setOpen(true);setMode('edit');setTimeout(()=>inputRef.current?.focus(),30);};
  const closeEditor=()=>{inputRef.current?.blur();setOpen(false);};
  const tableControls=()=>{if(!value.includes('|'))return null;const actions:[string,string,MarkdownCommand][]=[['Add row','Add table row','tableRow'],['Add column','Add table column','tableColumn'],['Remove row','Remove table row','tableRemoveRow'],['Remove column','Remove table column','tableRemoveColumn']];return <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{flexGrow:0,flexShrink:0}} contentContainerStyle={{flexDirection:'row',gap:6,paddingHorizontal:8,paddingBottom:8}} accessibilityLabel="Table controls">{actions.map(([label,hint,command])=><TouchableOpacity key={label} accessibilityRole="button" accessibilityLabel={hint} onPress={()=>tableAction(command)} style={{minWidth:44,minHeight:44,paddingHorizontal:10,alignItems:'center',justifyContent:'center',borderRadius:8,backgroundColor:colors.background}}><Text style={{color:colors.textMain,fontWeight:'700'}}>{label}</Text></TouchableOpacity>)}</ScrollView>;};
  const tableBuilderControls=()=>!tableBuilder?null:<View accessibilityLabel="Table builder" style={{flexDirection:'row',flexWrap:'wrap',gap:8,paddingHorizontal:8,paddingBottom:8,alignItems:'center'}}><Text style={{color:colors.textMuted,fontWeight:'700'}}>Rows</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel="Decrease table rows" disabled={tableRows<=1} onPress={()=>setTableRows(value=>Math.max(1,value-1))} style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><Text style={{color:colors.textMain}}>-</Text></TouchableOpacity><Text accessibilityLabel={`${tableRows} body rows`} style={{color:colors.textMain,minWidth:20,textAlign:'center'}}>{tableRows}</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel="Increase table rows" disabled={tableRows>=20} onPress={()=>setTableRows(value=>Math.min(20,value+1))} style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><Text style={{color:colors.textMain}}>+</Text></TouchableOpacity><Text style={{color:colors.textMuted,fontWeight:'700'}}>Columns</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel="Decrease table columns" disabled={tableColumns<=2} onPress={()=>setTableColumns(value=>Math.max(2,value-1))} style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><Text style={{color:colors.textMain}}>-</Text></TouchableOpacity><Text accessibilityLabel={`${tableColumns} columns`} style={{color:colors.textMain,minWidth:20,textAlign:'center'}}>{tableColumns}</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel="Increase table columns" disabled={tableColumns>=10} onPress={()=>setTableColumns(value=>Math.min(10,value+1))} style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><Text style={{color:colors.textMain}}>+</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Insert ${tableRows} by ${tableColumns} table`} onPress={insertTable} style={{minHeight:44,paddingHorizontal:14,alignItems:'center',justifyContent:'center',borderRadius:8,backgroundColor:colors.primary}}><Text style={{color:colors.textMain,fontWeight:'800'}}>Insert table</Text></TouchableOpacity></View>;
  const toolbar=(focus:boolean, compactMode=false)=><><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{flexDirection:'row',gap:6,padding:8,alignItems:'center'}} style={{flexGrow:0,flexShrink:0,borderBottomWidth:1,borderColor:colors.border}}>{(compactMode?TOOLS.slice(0,2):TOOLS.slice(0,6)).map(tool=><Tooltip key={tool.label} label={tool.label}><TouchableOpacity accessibilityRole="button" accessibilityLabel={tool.label} onPress={()=>insert(tool.command)} style={{minWidth:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:8,backgroundColor:colors.background}}><Text style={{color:colors.textMain,fontWeight:'800'}}>{tool.icon}</Text></TouchableOpacity></Tooltip>)}{!compactMode&&<>{focus&&<Tooltip label="Import Markdown"><TouchableOpacity accessibilityRole="button" accessibilityLabel="Import Markdown file" onPress={chooseMarkdownFile} style={{minWidth:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:8,backgroundColor:colors.background}}><FontAwesome name="file-text-o" size={14} color={colors.textMuted}/></TouchableOpacity></Tooltip>}<TouchableOpacity accessibilityRole="button" accessibilityLabel={advanced?'Hide advanced formatting':'Show advanced formatting'} accessibilityState={{expanded:advanced}} onPress={()=>setAdvanced(!advanced)} style={{minWidth:56,height:44,alignItems:'center',justifyContent:'center'}}><Text style={{color:colors.textMuted,fontWeight:'800'}}>More</Text></TouchableOpacity>{advanced&&TOOLS.slice(6).map(tool=><Tooltip key={tool.label} label={tool.label}><TouchableOpacity accessibilityRole="button" accessibilityLabel={tool.label} accessibilityState={tool.command==='table'?{expanded:tableBuilder}:undefined} onPress={()=>insert(tool.command)} style={{minWidth:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:8,backgroundColor:colors.background}}><Text style={{color:colors.textMain,fontWeight:'800'}}>{tool.icon}</Text></TouchableOpacity></Tooltip>)}<TouchableOpacity accessibilityRole="button" accessibilityLabel="Undo" onPress={undo} style={{minWidth:44,height:44,alignItems:'center',justifyContent:'center'}}><FontAwesome name="undo" size={14} color={colors.textMuted}/></TouchableOpacity><TouchableOpacity accessibilityRole="button" accessibilityLabel="Redo" onPress={redo} style={{minWidth:44,height:44,alignItems:'center',justifyContent:'center'}}><FontAwesome name="repeat" size={14} color={colors.textMuted}/></TouchableOpacity></>}<Tooltip label={focus?'Close expanded editor':'Expand editor'}><TouchableOpacity accessibilityRole="button" accessibilityLabel={focus?'Close expanded editor':'Expand editor'} onPress={()=>focus?closeEditor():openEditor()} style={{minWidth:44,height:44,alignItems:'center',justifyContent:'center'}}><FontAwesome name={focus?'compress':'expand'} size={14} color={colors.textMuted}/></TouchableOpacity></Tooltip></ScrollView>{!compactMode&&<>{tableBuilderControls()}{tableControls()}</>}</>;
  const handleEnter=(event:any)=>{const r=continueMarkdownOnEnter(value,selection);if(r.value!==value+'\n'){event.preventDefault?.();change(r.value);setSelection(r.selection);}};
  const renderInput=(compact:boolean)=><TextInput ref={inputRef} selection={selection} testID={compact&&testID?`${testID}-compact`:testID} value={value} onChangeText={change} onSelectionChange={e=>setSelection(e.nativeEvent.selection)} onKeyPress={Platform.OS==='web'?undefined:(e:any)=>{if(e.nativeEvent.key==='Enter')handleEnter(e);}} {...(Platform.OS==='web'?{onDoubleClick:compact?openEditor:undefined,onKeyDown:(e:any)=>{if(e.key==='Escape'&&tableBuilder){e.preventDefault();e.stopPropagation();setTableBuilder(false);return;}if(e.key==='Tab'){e.preventDefault();insert(e.shiftKey?'outdent':'indent');return;}if(e.key==='Enter'){handleEnter(e);return;}if((e.metaKey||e.ctrlKey)&&!e.altKey){const c=({b:'bold',i:'italic',k:'link',z:'undo',y:'redo'} as any)[String(e.key).toLowerCase()];if(c){e.preventDefault();c==='undo'?undo():c==='redo'?redo():insert(c);}}}}:{})} placeholder={placeholder} placeholderTextColor={colors.textDim} multiline textAlignVertical="top" style={{flex:1,minHeight,padding:14,color:colors.textMain,fontSize:14}}/>;
  const compact=!open&&<View style={{minHeight,borderWidth:1,borderColor:colors.border,borderRadius:12,overflow:'hidden'}}>{toolbar(false,sidebarMode)}{renderInput(true)}{previewLimited&&<Text accessibilityRole="alert" style={{paddingHorizontal:12,paddingVertical:6,color:colors.danger}}>Preview limit reached; all Markdown remains saved.</Text>}</View>;
  const desktop=width>=768;
  const expandedContent=(contentMode:'edit'|'preview')=>contentMode==='edit'?<View style={{flex:1,minHeight:0}}>{renderInput(false)}</View>:<ScrollView style={{flex:1,minHeight:0,padding:14}}><MarkdownDescription value={value}/></ScrollView>;
  const markdownDecision=markdownImport&&<View accessibilityRole="alert" style={{padding:12,borderBottomWidth:1,borderColor:colors.border,backgroundColor:colors.background}}><Text style={{color:colors.textMain,fontWeight:'800'}}>Import “{markdownImport.name}”?</Text>{markdownImport.unsupported.length>0&&<Text style={{color:colors.textMuted,marginTop:4}}>Imported as Markdown text. Some constructs may need review: {markdownImport.unsupported.join(', ')}.</Text>}<View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:8}}><TouchableOpacity accessibilityRole="button" accessibilityLabel="Insert imported Markdown at cursor" onPress={()=>applyMarkdownImport(markdownImport.source,importReviewNotice(markdownImport))} style={{minHeight:44,paddingHorizontal:14,alignItems:'center',justifyContent:'center',borderRadius:8,backgroundColor:colors.primary}}><Text style={{color:colors.textMain,fontWeight:'800'}}>Insert at cursor</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" accessibilityLabel="Replace description with imported Markdown" onPress={()=>{change(markdownImport.source);setSelection({start:markdownImport.source.length,end:markdownImport.source.length});setMarkdownImport(null);const notice=importReviewNotice(markdownImport);setMarkdownNotice(notice?{kind:'info',message:notice}:null);setMode('edit');setTimeout(()=>inputRef.current?.focus(),0);}} style={{minHeight:44,paddingHorizontal:14,alignItems:'center',justifyContent:'center',borderRadius:8,backgroundColor:colors.background}}><Text style={{color:colors.textMain,fontWeight:'800'}}>Replace description</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" accessibilityLabel="Cancel Markdown import" onPress={()=>setMarkdownImport(null)} style={{minHeight:44,paddingHorizontal:14,alignItems:'center',justifyContent:'center',borderRadius:8,backgroundColor:colors.background}}><Text style={{color:colors.textMuted,fontWeight:'800'}}>Cancel</Text></TouchableOpacity></View></View>;
  return <><View>{compact}</View>{open&&<Popup visible={open} onClose={closeEditor} presentation="auto" desktopBreakpoint={768} maxWidth={desktop?1100:720} maxHeight="94%" containerStyle={{height:'94%'}} title={focusTitle}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1,minHeight:0}}><View ref={markdownIntake.ref} onLayout={event=>setExpandedWidth(event.nativeEvent.layout.width)} style={{flex:1,minHeight:0}}>{toolbar(true)}{markdownIntake.isOver&&<Text accessibilityLabel="Markdown drop target active" style={{padding:8,color:colors.primary}}>Drop one Markdown file to import.</Text>}{markdownNotice&&<Text accessibilityRole="alert" style={{padding:8,color:markdownNotice.kind==='error'?colors.danger:colors.textMuted}}>{markdownNotice.message}</Text>}{markdownDecision}<View style={{flexDirection:'row',borderBottomWidth:1,borderColor:colors.border}}>{(['edit','preview'] as const).map(tab=><TouchableOpacity key={tab} onPress={()=>setMode(tab)} accessibilityRole="tab" accessibilityState={{selected:mode===tab}} accessibilityLabel={`${tab} description`} style={{flex:1,minHeight:44,alignItems:'center',justifyContent:'center'}}><Text style={{color:mode===tab?colors.primary:colors.textMuted,fontWeight:'800'}}>{tab.toUpperCase()}</Text></TouchableOpacity>)}{canSplit&&<TouchableOpacity onPress={()=>setMode('split')} accessibilityRole="tab" accessibilityState={{selected:mode==='split'}} accessibilityLabel="split description" style={{flex:1,minHeight:44,alignItems:'center',justifyContent:'center'}}><Text style={{color:mode==='split'?colors.primary:colors.textMuted,fontWeight:'800'}}>SPLIT</Text></TouchableOpacity>}</View>{previewLimited&&<Text accessibilityRole="alert" style={{paddingHorizontal:12,paddingVertical:6,color:colors.danger}}>Preview is limited to {MAX_INPUT.toLocaleString()} characters and {MAX_BLOCKS} blocks; all Markdown remains saved.</Text>}{mode==='split'?<View style={{flex:1,minHeight:0,flexDirection:'row'}}><View style={{flex:1,minHeight:0,borderRightWidth:1,borderColor:colors.border}}>{renderInput(false)}</View><ScrollView style={{flex:1,minHeight:0,padding:14}}><MarkdownDescription value={value}/></ScrollView></View>:expandedContent(mode)}</View></KeyboardAvoidingView></Popup>}</>;
}
