import assert from 'node:assert/strict';
import fs from 'node:fs';

const source = fs.readFileSync('contexts/TaskFilePasteContext.web.tsx', 'utf8');
const route = fs.readFileSync('app/task/[id].web.tsx', 'utf8');
const layout = fs.readFileSync('app/_layout.web.tsx', 'utf8');
assert.strictEqual((source.match(/useSmartPaste\(/g) ?? []).length, 1);
assert.match(source, /useSmartPaste\(\{ onFiles \}, activeEligible\)/);
assert.doesNotMatch(source, /onText/);
assert.match(source, /targetsRef/);
assert.match(source, /configRef\.current = config/);
assert.doesNotMatch(source, /\}, \[context, config\.id\]\)/);
assert.match(source, /registerTarget\(config\.id, configRef\)[\s\S]*?\}, \[registerTarget, config\.id\]\)/);
assert.match(source, /updateTarget\?\.\(config\.id\)[\s\S]*?\}, \[updateTarget, config\.id, config\.enabled\]\)/);
assert.match(source, /targetsRef\.current\.delete\(id\)/);
assert.match(source, /if \(targetsRef\.current\.get\(id\) !== configRef\) return;/);
assert.match(source, /armedIdRef\.current = null/);
assert.match(source, /return \(\) => \{[\s\S]*?targetsRef\.current\.delete\(id\);[\s\S]*?setRegistryVersion/);
assert.doesNotMatch(source, /targetsRef\.current\.delete\(id\);[\s\S]*?setArmedId\(null\)/);
assert.match(source, /useEffect\(\(\) => \(\) => \{[\s\S]*?targetsRef\.current\.clear\(\);[\s\S]*?armedIdRef\.current = null;/);
assert.match(source, /dedupeTaskFilePaste/);
assert.match(source, /infoToast\([\s\S]*?Paste destination armed/);
assert.match(source, /errorToast\([\s\S]*?Paste failed/);
assert.match(source, /const result = await target\.onFiles\(accepted\);[\s\S]*?if \(result === false\) return;/);
assert.doesNotMatch(route, /TaskFilePasteProvider/);
assert.match(layout, /import \{ TaskFilePasteProvider \} from ['"]@\/contexts\/TaskFilePasteContext['"]/);
assert.match(layout, /import \{ Slot, useLocalSearchParams|import \{ Slot, usePathname/);
assert.match(layout, /const pathname = usePathname\(\);/);
assert.match(layout, /<TaskFilePasteProvider key=\{pathname\}>[\s\S]*?\{showSidebar \? \(/);
assert.match(layout, /\)[\s\S]*?<\/TaskFilePasteProvider>/);
console.log('TaskFilePasteContext source check: ok');
