/**
 * Web file transfer: download generated bytes via a Blob/anchor, and pick a
 * local spreadsheet via a hidden <input type="file">. The native counterpart
 * lives in fileTransfer.native.ts (expo-file-system + expo-document-picker).
 */

export type PickedFile = { name: string; bytes: Uint8Array };

export async function saveBytes(
  filename: string,
  bytes: Uint8Array,
  mime: string
): Promise<string | null> {
  const blob = new Blob([bytes as unknown as BlobPart], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.visibility = 'hidden';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  return filename;
}

export function pickSpreadsheet(): Promise<PickedFile | null> {
  return new Promise(resolve => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept =
      '.csv,.xlsx,.xls,text/csv,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    input.onchange = async () => {
      const file = input.files?.[0];
      if (!file) return resolve(null);
      try {
        const buf = await file.arrayBuffer();
        resolve({ name: file.name, bytes: new Uint8Array(buf) });
      } catch {
        resolve(null);
      }
    };
    input.click();
  });
}
