// Canonical FontAwesome icon registry.
//
// Components should import ICONS.X and pass it to <FontAwesome name={...}/>
// instead of hardcoding FontAwesome name strings, so icon meaning stays
// centralized in one place and semantic keys map to glyphs consistently
// across the app (see issue #263).

export const ICONS = {
  ADD: 'plus',
  ADD_CIRCLE: 'plus-circle',
  DELETE: 'trash-o',
  EDIT: 'pencil-square-o',
  CLOSE: 'times',
  CANCEL: 'times-circle',
  DUPLICATE: 'clone',
  COPY: 'copy',
  DOWNLOAD: 'download',
  UPLOAD: 'cloud-upload',
  REFRESH: 'refresh',
  UNDO: 'undo',
  SAVE: 'save',
  SEND: 'paper-plane-o',
  LINK: 'link',
  SHARE: 'share-alt',
  PRINT: 'print',
  CHEVRON_UP: 'chevron-up',
  CHEVRON_DOWN: 'chevron-down',
  CHEVRON_LEFT: 'chevron-left',
  CHEVRON_RIGHT: 'chevron-right',
  BACK: 'chevron-left',
  FORWARD: 'chevron-right',
  ARROW_LEFT: 'arrow-left',
  ARROW_RIGHT: 'arrow-right',
  DRAG: 'arrows',
  EXTERNAL_LINK: 'external-link',
  SUCCESS: 'check-circle',
  CHECK: 'check',
  WARNING: 'exclamation-triangle',
  DANGER: 'exclamation-circle',
  INFO: 'info-circle',
  HELP: 'question-circle',
  PENDING: 'clock-o',
  BLOCKED: 'ban',
  LOCKED: 'lock',
  SEARCH: 'search',
  FILTER: 'filter',
  SETTINGS: 'gear',
  ADVANCED_SETTINGS: 'sliders',
  SORT: 'sort',
  VIEW: 'eye',
  HIDE: 'eye-slash',
  CALENDAR: 'calendar-o',
  CALENDAR_EMPTY: 'calendar-o',
  CLOCK: 'clock-o',
  BELL: 'bell-o',
  BELL_EMPTY: 'bell-o',
  FOLDER: 'folder-o',
  FOLDER_OPEN: 'folder-open-o',
  FILE: 'file-o',
  FILE_PDF: 'file-pdf-o',
  FILE_WORD: 'file-word-o',
  FILE_EXCEL: 'file-excel-o',
  FILE_IMAGE: 'file-image-o',
  FILE_AUDIO: 'file-audio-o',
  FILE_VIDEO: 'file-video-o',
  FILE_ZIP: 'file-zip-o',
  FILE_TEXT: 'file-text-o',
  ARCHIVE: 'archive',
  INBOX: 'inbox',
  CLIPBOARD: 'clipboard',
  USER: 'user',
  USER_ADD: 'user-plus',
  USERS: 'users',
  BUILDING: 'briefcase',
  BRIEFCASE: 'briefcase',
  KEY: 'key',
  GLOBE: 'globe',
  STAR: 'star',
  STAR_EMPTY: 'star-o',
  FLAG: 'flag',
  FLAG_EMPTY: 'flag-o',
  BAR_CHART: 'bar-chart',
  LINE_CHART: 'line-chart',
  AREA_CHART: 'area-chart',
  TARGET: 'bullseye',
  HISTORY: 'history',
  DASHBOARD: 'th-large',
  OVERVIEW: 'th-large',
  PORTFOLIO: 'cubes',
  REPORT: 'file-pdf-o',
} as const;

export type IconKey = keyof typeof ICONS;
export type IconName = (typeof ICONS)[IconKey];
