import assert from 'node:assert';
import { applyMarkdownCommand, continueMarkdownOnEnter, createMarkdownTable, isAllowedMarkdownHref, markdownExcerpt, markdownToPlainText, parseTaskDescriptionMarkdown } from './taskDescriptionMarkdown';

assert.equal(markdownToPlainText('# Title\n\n**bold** *italic* ~~old~~ `code`'), 'Title\nbold italic old code');
assert.equal(markdownToPlainText('- [x] Done\n- Open\n\n> quote\n\n---'), 'Done\nOpen\nquote');
assert.equal(markdownToPlainText('| A | B |\n|---|---|\n| 1 | 2 |'), 'A | B\n1 | 2');
assert.equal(parseTaskDescriptionMarkdown('<b>literal</b>')[0].type, 'paragraph');
assert.equal(isAllowedMarkdownHref('javascript:alert(1)'), false);
assert.equal(isAllowedMarkdownHref('https://example.com'), true);
assert.equal(isAllowedMarkdownHref('https://'), false);
assert.equal(isAllowedMarkdownHref('javascript:alert(1)'), false);
assert.deepEqual(applyMarkdownCommand('abc', { start: 1, end: 2 }, 'bold').value, 'a**b**c');
assert.deepEqual(applyMarkdownCommand('abc', { start: 1, end: 1 }, 'italic').selection, { start: 2, end: 2 });
assert.equal(applyMarkdownCommand('a\nb', { start: 0, end: 3 }, 'bullet').value, '- a\n- b');
assert.deepEqual(applyMarkdownCommand('a\nb', { start: 0, end: 3 }, 'bullet').selection, { start: 2, end: 7 });
assert.equal(applyMarkdownCommand('- a', { start: 2, end: 3 }, 'number').value, '1. a');
assert.equal(applyMarkdownCommand('**bold**', { start: 2, end: 6 }, 'bold').value, 'bold');
assert.equal(continueMarkdownOnEnter('- [x] done', 10).value, '- [x] done\n- [ ] ');
assert.equal(continueMarkdownOnEnter('- [ ] ', 6).value, '\n');
assert.equal(continueMarkdownOnEnter('- first\n- second', { start: 2, end: 7 }).value, '-\n- second');
assert.deepEqual(applyMarkdownCommand('  a\n  b', { start: 0, end: 7 }, 'outdent').selection, { start: 0, end: 3 });
assert.match(applyMarkdownCommand('', { start: 0, end: 0 }, 'link').value, /^\[link text\]\(https:\/\/example\.com\)$/);
assert.equal(applyMarkdownCommand('', { start: 0, end: 0 }, 'table').value, '| Header | Value |\n| --- | --- |\n| Cell | Cell |');
assert.equal(createMarkdownTable(2, 3), '| Header | Value | Column 3 |\n| --- | --- | --- |\n| Cell | Cell | Cell |\n| Cell | Cell | Cell |');
const table = createMarkdownTable(1, 2);
assert.equal(applyMarkdownCommand(table, { start: 0, end: table.length }, 'tableRow').value, `${table}\n| Cell | Cell |`);
assert.equal(applyMarkdownCommand(table, { start: 0, end: table.length }, 'tableColumn').value, '| Header | Value | Cell |\n| --- | --- | --- |\n| Cell | Cell | Cell |');
assert.equal(applyMarkdownCommand(createMarkdownTable(2, 2), { start: 0, end: createMarkdownTable(2, 2).length }, 'tableRemoveRow').value, table);
assert.equal(applyMarkdownCommand('abc', { start: 99, end: 120 }, 'bold').value, 'abc****');
assert.doesNotThrow(() => markdownToPlainText('*x*'.repeat(1000)));
assert.equal(markdownExcerpt('one two three', 8), 'one two…');
console.log('taskDescriptionMarkdown: all assertions passed');
