// Focused source check for upload scope seeding and folder integrity.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import assert from 'node:assert/strict';

const source = readFileSync(join(process.cwd(), 'components/filehub/UploadComposerModal.web.tsx'), 'utf8');
const nativeSource = readFileSync(join(process.cwd(), 'components/filehub/UploadComposerModal.tsx'), 'utf8');
const uploadManagerSource = readFileSync(join(process.cwd(), 'contexts/UploadManagerContext.tsx'), 'utf8');

assert.match(source, /visibilitySeed\?: 'direct' \| 'broadcast'/, 'web composer visibility seed prop missing');
assert.match(source, /destination\?: UploadDestination/, 'web composer destination prop missing');
assert.match(source, /rpc\('rpc_project_files'/, 'project composer must load the authorized workspace');
assert.match(source, /isProjectDestination \? 'project'/, 'project composer must use project visibility');
assert.match(source, /destination,/, 'web composer must pass destination to the manager');
assert.match(source, /destination: isProjectDestination && destination \? \{ \.\.\.destination, folderId: draft\.folderId \} : destination/, 'project uploads must pass the selected draft folder to the manager');
assert.match(source, /audienceControls = isProjectDestination \? null/, 'project mode must hide audience controls');
assert.match(source, /!isProjectDestination && draft\.visibility === 'direct'/, 'project mode must hide recipient controls');
assert.match(source, /authorizedFolderIds\.has\(destination\.folderId\)/, 'project destination must validate the requested folder');
assert.match(source, /isProjectDestination[\s\S]*scopedFolders\.some\(folder => folder\.id === draft\.folderId\)/, 'project upload must reject invalid folder ids');
assert.match(source, /activeGroup \? 'group' : visibilitySeed \?\? 'direct'/, 'group/default visibility seed precedence missing');
assert.match(source, /folder\.id === prev\.folderId/, 'folder scope validation missing');
assert.match(source, /folderId: null/, 'invalid scoped folder is not cleared');
assert.match(source, /folderId !== undefined \? folderId : prev\.folderId/, 'valid initial folder preservation guard missing');
assert.match(source, /data, error.*!error/s, 'folder fetch error guard missing');
assert.match(source, /Map<string, MemberSummary>/, 'recipient records must be canonicalized by id with concrete type');
assert.match(source, /recipientRequestRef/, 'recipient search stale-response guard missing');
assert.match(source, /setTimeout\(async/, 'recipient search debounce missing');
assert.match(source, /recipientIds: selectedRecipientIds/, 'upload payload must derive recipient ids at upload time');
assert.match(source, /query=\{recipientSearch\}.*onQueryChange=\{setRecipientSearch\}/s, 'searchable recipient query API missing');
assert.doesNotMatch(source, /visibility: opt\.value as any, recipientIds: \[\]/, 'visibility changes must preserve selected recipients');
assert.match(source, /type MemberSummary =/, 'member records need a concrete summary type');
assert.doesNotMatch(source, /setRecipientRecords\(prev => \{[\s\S]*rows\.forEach/, 'search results must not become selected recipients');
assert.match(source, /className="w-11 h-11 items-center justify-center rounded-xl border"/, 'audience selector must use compact 44x44 controls');
assert.doesNotMatch(source, /Direct Send/, 'large direct-send visibility control should be removed');
assert.match(source, /isDesktop \|\| mobilePage === 'form'/, 'picker pages must omit the upload footer');
assert.match(source, /isDesktop && !isProjectDestination && draft\.visibility === 'direct'.*SearchableMultiSelect/s, 'full recipient picker must be desktop-only and global-only in form page');
assert.match(source, /Destination[\s\S]*setDetailsOpen[\s\S]*Tags[\s\S]*Caption/, 'destination must remain outside optional details while tags/caption are inside');
assert.match(source, /finishPicker.*w-11 h-11/, 'mobile picker back control must be 44x44');
assert.match(source, /from\('users'\).*order\('full_name'\).*if \(query\)/s, 'blank recipient query must load default alphabetical members');
assert.match(source, /new Map\(\(data \|\| \[\]\)\.map/, 'member result rows must be deduplicated');
assert.match(source, /autoFocus onClearSelection/, 'mobile recipient picker must autofocus and expose explicit clear selection');
assert.match(source, /Done choosing destination/, 'mobile picker needs a Done action');
assert.match(source, /Clear all staged files/, 'file staging needs explicit clear-all affordance');
assert.match(source, /No details/, 'empty details summary must be explicit');
assert.match(source, /\[recipientSearch, visible\]/, 'recipient defaults must reload when modal becomes visible');
assert.match(source, /setDetailsOpen\(false\)/, 'details must reset on close');
assert.match(source, /Top level \(no folder\)/, 'empty destination needs explicit root copy');
assert.match(source, /w-11 h-11 bg-black\/50/, 'file tile remove controls must be 44px');
assert.match(source, /setSearchingMembers\(false\)/, 'close must reset member loading state');
assert.match(source, /keyboardShouldPersistTaps="handled"/, 'picker search must preserve taps while keyboard is open');
assert.match(source, /Done choosing recipients.*Done choosing destination/s, 'picker Done label must reflect active picker');
assert.match(source, /accessibilityLabel="Add more files"/, 'internal Add More tile needs accessibility label');
assert.match(source, /mobilePage === 'recipients'\) finishPicker/, 'audience switch must clean up recipient picker state');
assert.match(source, /Left column:[\s\S]*flexGrow: 2, flexBasis: 0, minWidth: 0/, 'file pane must shrink and wrap instead of forcing metadata overflow');
assert.match(source, /Right column:[\s\S]*flexGrow: 3, flexBasis: 0, minWidth: 0/, 'metadata pane must retain enough desktop width for its controls');
assert.match(source, /desktopDestinationOpen/, 'desktop destination picker state missing');
assert.match(source, /Choose destination folder/, 'desktop destination summary trigger missing');
assert.match(source, /Choose destination[\s\S]*Back to upload form/, 'desktop picker needs an in-place back header');
assert.match(source, /Search destination folders/, 'desktop destination picker needs controlled folder search');
assert.match(source, /desktopDestinationSearch.*setDesktopDestinationSearch/s, 'desktop destination search must be controlled');
assert.match(source, /folderAncestors\(scopedFolders, folder\.id\)/, 'folder search must retain matching ancestors');
assert.match(source, /\{!isProjectDestination && <input ref=\{folderInputRef\}/, 'project mode must not offer browser folder uploads that the project commit RPC rejects');
assert.match(source, /\{!isProjectDestination && <TouchableOpacity[\s\S]*accessibilityLabel="Choose folder"/, 'project mode must require explicit workspace folder selection');
assert.match(source, /Select top level/, 'desktop picker needs explicit root selection');
assert.match(source, /Selected destination/, 'desktop picker must show the selected full path');
assert.match(source, /<ScrollView[\s\S]*<FolderTreePicker[\s\S]*scrollable=\{false\}/, 'desktop picker must own one bounded scroll around a non-scrolling tree');
assert.equal((source.match(/<Popup\b/g) || []).length, 1, 'desktop destination must reuse the outer Popup');
assert.match(nativeSource, /destination\?: UploadDestination/, 'native composer destination prop missing');
assert.doesNotMatch(nativeSource, /useRouter|router\.push/, 'native composer must not redirect global uploads back into FileHub');
assert.match(nativeSource, /expo-file-system/, 'native composer must use Expo filesystem files, not browser-only File wrappers');
assert.doesNotMatch(nativeSource, /new File\(\[blob\]/, 'native composer must not construct a browser File from a React Native Blob');
assert.match(uploadManagerSource, /job\.destination\?\.kind === 'project'[\s\S]*relativeDirectory/, 'project uploads must reject dropped folder paths');
assert.match(uploadManagerSource, /Project folder uploads are not supported/, 'project folder upload rejection must be actionable');
assert.match(nativeSource, /rpc\('rpc_project_files'/, 'native composer must load the project workspace');
assert.match(nativeSource, /startUpload\(/, 'native composer must use UploadManagerContext for every target');
assert.match(nativeSource, /kind: 'filehub'/, 'native composer must support global FileHub destinations');
assert.match(nativeSource, /visibility: uploadVisibility/, 'native composer must preserve the selected visibility');
assert.match(nativeSource, /activeGroup\?\.id/, 'native composer must preserve channel targets');
assert.match(nativeSource, /SearchableMultiSelect/, 'native direct uploads must retain recipient selection');
assert.match(nativeSource, /DocumentPicker\.getDocumentAsync/, 'native composer must own native file intake');
assert.match(nativeSource, /authorizedFolderIds\.has\(destination\.folderId\)/, 'native project destination must validate the requested folder');
assert.match(nativeSource, /scopedFolders\.some\(folder => folder\.id === draft\.folderId\)/, 'native upload must reject invalid folder ids');
assert.match(nativeSource, /<Popup\b/, 'native composer must use Popup');

const dispatchSource = readFileSync(join(process.cwd(), 'contexts/ModalDispatchContext.tsx'), 'utf8');
const hostSource = readFileSync(join(process.cwd(), 'components/common/ModalHost.tsx'), 'utf8');
assert.match(dispatchSource, /destination\?: UploadDestination/, 'modal dispatch must carry upload destinations');
assert.match(hostSource, /destination=\{active\.payload\.destination\}/, 'modal host must propagate upload destinations');

console.log('UploadComposerModal.check: ok');
