import { useFileHub } from '@/contexts/FileHubContext';
import { useDoubleTap } from '@/hooks/useDoubleTap';
import { useImageLightbox, type LightboxMedia } from '@/hooks/useImageLightbox';
import { useThemeColors } from '@/hooks/useThemeColors';
import { downloadFilesAsZip, openStorageFile } from '@/lib/storage';
import { supabase } from '@/lib/supabase';
import { isMultiSelectModifierActive, webModifierKeys } from '@/lib/webModifierKeys';
import { FontAwesome } from '@expo/vector-icons';
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Text, TouchableOpacity, View } from 'react-native';
import FilterPanel, { FilterChipGroup, FilterDropdown, FilterSection } from '../common/FilterPanel';
import { FilePreviewCard } from '../common/FilePreviewCard';
import Tooltip from '../common/Tooltip';
import ExplorerCollection from '../filehub/explorer/ExplorerCollection';
import FileHubDetailPane, { type DetailFile } from './FileHubDetailPane';
import { useShareFile } from '../common/ShareFile';
import { fileIcon, formatSize } from './TaskFileResults';
import { getBrowseOriginLabel } from './filehubShared';

type BrowseItem = { source: 'filehub' | 'submission' | 'task_brief'; file_id: string; canonical_file_id: string | null; canonical_version_id: string | null; workspace_folder_id: string | null; workspace_path: string | null; origin: 'workspace' | 'deliverable' | 'shared' | 'brief' | 'submission' | null; bucket: string; storage_path: string; file_name: string; mime_type: string | null; size_bytes: number; created_at: string; task_id: string | null; task_title: string | null; project_id: string | null; project_name: string | null; task_category: string | null; submission_id: string | null };
type Facets = { projects: { id: string; name: string; count: number }[]; categories: { category: string; count: number }[]; types: { type: string; count: number }[]; origins: { origin: BrowseItem['origin']; count: number }[] };
const PAGE = 60; const ORIGIN_OPTIONS = ['workspace', 'deliverable', 'shared', 'brief', 'submission']; const SOURCE_TABS = [{ label: 'All', value: null }, { label: 'FileHub', value: ['filehub'] }, { label: 'Submissions', value: ['submission'] }, { label: 'Briefs', value: ['task_brief'] }] as const; const idOf = (it: BrowseItem) => `${it.source}:${it.file_id}`; const isImage = (m: string | null) => !!m && m.toLowerCase().includes('image');
export default function FileHubBrowse({ compact }: { compact?: boolean }) {
  const colors = useThemeColors(); const { searchDebounced } = useFileHub(); const { share, shareSheet } = useShareFile(); const [sourceTab, setSourceTab] = useState(0); const [projectId, setProjectId] = useState<string | null>(null); const [origin, setOrigin] = useState<string | null>(null); const [category, setCategory] = useState<string | null>(null); const [type, setType] = useState<string | null>(null); const [items, setItems] = useState<BrowseItem[]>([]); const [facets, setFacets] = useState<Facets | null>(null); const [hasMore, setHasMore] = useState(false); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set()); const [anchorIdx, setAnchorIdx] = useState<number | null>(null); const [detail, setDetail] = useState<BrowseItem | null>(null); const [fastPreview, setFastPreview] = useState(false); const [zipping, setZipping] = useState(false); const [filtersOpen, setFiltersOpen] = useState(false); const isDoubleTap = useDoubleTap(); const sources = SOURCE_TABS[sourceTab].value;
  const media: LightboxMedia[] = useMemo(() => items.map(it => ({ id: idOf(it), name: it.file_name, storagePath: it.storage_path, mimeType: it.mime_type, bucket: it.bucket, sizeBytes: it.size_bytes })), [items]); const { signedUrls } = useImageLightbox(media, 'filehub-files');
  const fetchPage = useCallback(async (before: string | null, withFacets: boolean) => { const { data, error } = await supabase.rpc('rpc_filehub_browse', { p_query: searchDebounced || null, p_sources: sources, p_project_id: projectId, p_origins: origin ? [origin] : null, p_category: category, p_type: type, p_before: before, p_limit: PAGE, p_include_facets: withFacets }); if (error) { console.error('[FileHubBrowse] error', error); return { items: [] as BrowseItem[], has_more: false, facets: null }; } return data as { items: BrowseItem[]; has_more: boolean; facets: Facets | null }; }, [searchDebounced, sources, projectId, origin, category, type]);
  useEffect(() => { let cancelled = false; setLoading(true); setDetail(null); setSelectedIds(new Set()); setAnchorIdx(null); fetchPage(null, true).then(res => { if (!cancelled) { setItems(res.items); setHasMore(res.has_more); setFacets(res.facets); setLoading(false); } }); return () => { cancelled = true; }; }, [fetchPage]);
  const loadMore = async () => { if (loadingMore || !items.length) return; setLoadingMore(true); const res = await fetchPage(items[items.length - 1].created_at, false); setItems(previous => [...previous, ...res.items]); setHasMore(res.has_more); setLoadingMore(false); };
  const toggleOne = (it: BrowseItem, idx: number) => { setSelectedIds(previous => { const next = new Set(previous); const id = idOf(it); next.has(id) ? next.delete(id) : next.add(id); return next; }); setAnchorIdx(idx); };
  const onItemPress = (it: BrowseItem) => { const idx = items.findIndex(row => idOf(row) === idOf(it)); if (webModifierKeys.shift && anchorIdx !== null) { const [a, b] = [anchorIdx, idx].sort((x, y) => x - y); setSelectedIds(previous => { const next = new Set(previous); for (let i = a; i <= b; i++) next.add(idOf(items[i])); return next; }); return; } if (isMultiSelectModifierActive()) { toggleOne(it, idx); return; } setFastPreview(isDoubleTap(idOf(it))); setDetail(it); setAnchorIdx(idx); };
  const selectedItems = items.filter(it => selectedIds.has(idOf(it))); const shareItem = (it: BrowseItem) => share({ fileId: it.source === 'filehub' ? it.file_id : null, bucket: it.bucket, storagePath: it.storage_path, name: it.file_name, mimeType: it.mime_type, sizeBytes: it.size_bytes }); const downloadSelected = async () => { if (!selectedItems.length || zipping) return; setZipping(true); try { await downloadFilesAsZip(selectedItems.map(it => ({ storage_path: it.storage_path, bucket: it.bucket, original_name: it.file_name, mime_type: it.mime_type })), `filehub-${selectedItems.length}-files.zip`); } finally { setZipping(false); } };
  const filterCount = [projectId, origin, category, type].filter(Boolean).length; const clearFilters = () => { setProjectId(null); setOrigin(null); setCategory(null); setType(null); }; const filterBody = <View className="px-4 pt-4"><View className="flex-row flex-wrap gap-4"><FilterDropdown label="Project" count={projectId ? 1 : 0} selected={projectId ? [projectId] : []} options={(facets?.projects ?? []).map(p => ({ value: p.id, label: p.name || 'Untitled' }))} onToggle={v => setProjectId(projectId === v ? null : v)} /><FilterDropdown label="Origin" count={origin ? 1 : 0} selected={origin ? [origin] : []} options={ORIGIN_OPTIONS.map(value => ({ value, label: getBrowseOriginLabel(value) }))} onToggle={v => setOrigin(origin === v ? null : v)} /><FilterDropdown label="Category" count={category ? 1 : 0} selected={category ? [category] : []} options={(facets?.categories ?? []).map(c => ({ value: c.category, label: c.category }))} onToggle={v => setCategory(category === v ? null : v)} /><FilterDropdown label="Type" count={type ? 1 : 0} selected={type ? [type] : []} options={(facets?.types ?? []).map(t => ({ value: t.type, label: t.type }))} onToggle={v => setType(type === v ? null : v)} /></View><FilterSection label="Origin shortcuts" compact><FilterChipGroup horizontal>{ORIGIN_OPTIONS.map(value => <TouchableOpacity key={value} onPress={() => setOrigin(origin === value ? null : value)} className={`px-3 py-2 rounded-xl border ${origin === value ? 'bg-brand-primary/10 border-brand-primary' : 'bg-surface-card border-surface-border'}`}><Text className={origin === value ? 'text-brand-primary text-xs font-bold' : 'text-typography-muted text-xs font-bold'}>{getBrowseOriginLabel(value)}</Text></TouchableOpacity>)}</FilterChipGroup></FilterSection><TouchableOpacity disabled={!filterCount} onPress={clearFilters} className="self-end px-3 py-2"><Text className="text-state-danger text-xs font-black">Clear Filters</Text></TouchableOpacity></View>;
  const detailFile: DetailFile | null = detail && { ...detail }; const collection = <ExplorerCollection {...({ items, keyExtractor: idOf, storageKey: 'filehub-global-browse', defaultMode: 'details', modes: ['large', 'medium', 'list', 'details'], loading, emptyState: { icon: 'folder-open-o', title: 'No files found', body: searchDebounced ? `Nothing matches “${searchDebounced}” with these filters.` : 'Try a different filter.' }, onItemPress, onEndReached: hasMore ? loadMore : undefined, listFooter: loadingMore ? <View className="py-4 items-center"><ActivityIndicator color={colors.primary} /> </View> : null, testIDPrefix: 'filehub-browse', renderCard: (it: BrowseItem) => <FilePreviewCard fileName={it.file_name} mimeType={it.mime_type} subtitle={[it.project_name || it.task_title, getBrowseOriginLabel(it.origin), formatSize(it.size_bytes)].filter(Boolean).join(' · ')} imageUri={isImage(it.mime_type) ? signedUrls[idOf(it)] : undefined} sizeBytes={it.size_bytes} onPress={() => onItemPress(it)} />, renderRow: (it: BrowseItem) => <BrowseRow item={it} colors={colors} onDownload={() => openStorageFile(it.bucket, it.storage_path, it.file_name, it.mime_type)} onShare={() => shareItem(it)} />, columns: [{ key: 'name', label: 'File', flex: 2, render: (it: BrowseItem) => <BrowseRow item={it} colors={colors} /> }, { key: 'origin', label: 'Origin', render: (it: BrowseItem) => <Text className="text-typography-muted text-xs">{getBrowseOriginLabel(it.origin)}</Text> }, { key: 'project', label: 'Project', render: (it: BrowseItem) => <Text className="text-typography-muted text-xs">{it.project_name || '—'}</Text> }, { key: 'size', label: 'Size', align: 'right', render: (it: BrowseItem) => <Text className="text-typography-muted text-xs">{formatSize(it.size_bytes)}</Text> }] } as any)} />;
  return <View className="flex-1"><View className="px-4 pt-4 flex-row items-center gap-2">{SOURCE_TABS.map((tab, index) => <TouchableOpacity key={tab.label} onPress={() => { setSourceTab(index); clearFilters(); }} className={`px-4 py-2 rounded-xl border ${sourceTab === index ? 'bg-brand-primary/10 border-brand-primary' : 'bg-surface-card border-surface-border'}`}><Text className={sourceTab === index ? 'text-brand-primary text-xs font-black' : 'text-typography-muted text-xs font-black'}>{tab.label}</Text></TouchableOpacity>)}<View className="flex-1" /><FilterPanel isOpen={filtersOpen} onOpenChange={setFiltersOpen} activeCount={filterCount} trigger={({ toggle }) => <Tooltip label="Filters"><TouchableOpacity accessibilityLabel="Filters" onPress={toggle} className="h-10 w-10 items-center justify-center rounded-xl border border-surface-border bg-surface-card"><FontAwesome name="filter" size={13} color={colors.textMuted} /></TouchableOpacity></Tooltip>}>{filterBody}</FilterPanel></View><View className="flex-1 p-4">{collection}</View>{selectedItems.length > 0 && <View className="absolute bottom-4 left-4 right-4 rounded-2xl border border-brand-primary/30 bg-surface-card px-4 py-3 flex-row items-center gap-3"><Text className="text-brand-primary text-xs font-black">{selectedItems.length} selected</Text><View className="flex-1" /><TouchableOpacity disabled={zipping} onPress={downloadSelected} className="px-3 py-2 rounded-xl bg-brand-primary flex-row items-center gap-2">{zipping && <ActivityIndicator size="small" color="#fff" />}<Text className="text-white text-xs font-black">Download ZIP</Text></TouchableOpacity><TouchableOpacity onPress={() => setSelectedIds(new Set())} className="p-2"><FontAwesome name="times" size={13} color={colors.textMuted} /></TouchableOpacity></View>}{detailFile && <View className={compact ? 'absolute inset-0 bg-surface-background p-4' : 'absolute inset-4 bg-surface-background border border-surface-border rounded-2xl p-4'}><FileHubDetailPane file={detailFile} onClose={() => setDetail(null)} compact={compact} autoPreview={fastPreview} /></View>}{shareSheet}</View>;
}
function BrowseRow({ item, colors, onDownload, onShare }: { item: BrowseItem; colors: any; onDownload?: () => void; onShare?: () => void }) { return <View className="flex-row items-center gap-3 flex-1"><FontAwesome name={fileIcon(item.mime_type)} size={16} color={colors.textMuted} /><View className="flex-1 min-w-0"><Text numberOfLines={1} className="text-typography-main text-sm font-bold">{item.file_name}</Text><Text numberOfLines={1} className="text-typography-muted text-[11px]">{[item.project_name || item.task_title, getBrowseOriginLabel(item.origin), formatSize(item.size_bytes)].filter(Boolean).join(' · ')}</Text></View>{onDownload && <Tooltip label="Download"><TouchableOpacity onPress={e => { e.stopPropagation(); onDownload(); }} className="w-8 h-8 rounded-lg items-center justify-center border border-surface-border"><FontAwesome name="download" size={11} color={colors.textMuted} /></TouchableOpacity></Tooltip>}{onShare && <Tooltip label="Share file"><TouchableOpacity onPress={e => { e.stopPropagation(); onShare(); }} className="w-8 h-8 rounded-lg items-center justify-center border border-surface-border"><FontAwesome name="share" size={11} color={colors.textMuted} /></TouchableOpacity></Tooltip>}</View>; }
