// The MESSINESS dimension of the test corpus (plan §21.4). Data only — same
// contract as corpus.ts: no assertions, no I/O, ground truth authored beside
// the cells before the classifier is run over them.
//
// WHY THIS EXISTS, and why it is a separate file
// corpus.ts asks "does content-first classification generalise past one
// industry?" and answers it across eleven of them. It does NOT ask the question
// §21 is about, which is: what happens when the data was already broken before
// it reached us? Its whole trap vocabulary is three values — continuation,
// footer, subtotal — and its cells are clean.
//
// That gap is not theoretical. The eleven workbooks scored 127/128 primitives
// and missed the Excel-serial defect entirely; a real client file found it in
// one import. Synthetic fixtures are written by someone who knows what a date
// is, so they contain the mess we already imagined. These five contain the mess
// a spreadsheet, a browser or a tired human introduces on the way in.
//
// Scored SEPARATELY from the eleven (see benchmark.ts) so an improvement here
// can never hide a regression there.
//
// NO REAL DATA. Every company, person, email, phone and reference below is
// invented, as in corpus.ts.
//
// GROUND TRUTH CORRECTIONS MADE ONCE, AND ONLY FOR FACT. Two columns here were
// first authored `unique_id` and then corrected to `freetext` — not because the
// classifier disagreed, but because the cells I wrote genuinely repeat (a
// supplier books more than one event; three clients each get a "Statutory audit
// 2025"). "Service" was NOT corrected: 7 categories over 10 rows is an enum by
// any reading, the classifier calls it freetext, and that stays a miss.

import type { SheetCell } from '../spreadsheetMapping';
import type { WorkbookSpec } from './corpus';

// ─── the round-trip generator (plan §21.4) ─────────────────────────────────
// The one fixture-building technique corpus.ts does not use: rather than write
// down the END STATE of a corruption, put the data through the failure mode and
// keep whatever comes out.

/** Excel's day serial, on the 1899-12-30 epoch `parseDateValue` reads back. */
const serialOf = (y: number, m: number, d: number): number =>
  Math.round((Date.UTC(y, m - 1, d) - Date.UTC(1899, 11, 30)) / 86400000);

/**
 * A human types a `d/m/y` date into an Excel whose locale is `m/d/y`.
 *
 *   day <= 12 — a legal month, so Excel ACCEPTS it with the parts swapped and
 *               stores that serial. `8/2/26` meaning 8 February becomes 2
 *               August, and the cell displays "8/2/26" straight back at its
 *               author. Nothing looks wrong at any point.
 *   day  > 12 — there is no 15th month, so Excel gives up and keeps the literal
 *               text. Which is why exactly those cells survive CORRECT, and why
 *               they are also the evidence that settles the rest (§21.1).
 *
 * The asymmetry is the whole fixture: it is not possible to eyeball which rows
 * are wrong, because the wrong ones are the ones that still parse.
 */
export function typedDmyIntoMdyExcel(day: number, month: number, year: number): SheetCell {
  return day <= 12 ? serialOf(year, day, month) : `${day}/${month}/${year}`;
}

/** intended dates, in the order a human typed them, d/m/y */
const TARGETS: [number, number, number][] = [
  [15, 2, 2026], [8, 2, 2026], [3, 2, 2026], [22, 1, 2026], [10, 2, 2026], [28, 2, 2026],
  [1, 3, 2026], [17, 3, 2026], [9, 3, 2026], [25, 3, 2026], [12, 4, 2026], [4, 4, 2026],
];
const target = (i: number) => typedDmyIntoMdyExcel(...TARGETS[i]);

// ─── M1. The round-tripped workbook ────────────────────────────────────────

const MDY_ROUNDTRIP: WorkbookSpec = {
  id: 'messy-mdy-roundtrip',
  industry: 'Advisory — deadline register, typed into an MDY-locale Excel',
  headerRow: 0,
  nameColumn: 0,
  notes:
    'Col 3 "Target Date" is NOT written as dates — it is generated by pushing twelve d/m/y dates through ' +
    'an MDY-locale Excel, so seven of them are serials for the WRONG day and five survived as correct ' +
    'text. Cols 4 and 5 are clean date columns in the same sheet: whatever detects col 3 must leave ' +
    'them alone, or it is a false-positive machine rather than a detector.',
  columns: [
    { header: 'Engagement', primitive: 'unique_id', note: 'THE entity name' },
    { header: 'Client', primitive: 'enum' },
    { header: 'Partner', primitive: 'enum' },
    {
      header: 'Target Date', primitive: 'date', dateOrder: 'DMY',
      anomalies: ['mixed_date_encoding'],
      note: 'THE TRAP: 7 serials (day <= 12, silently swapped) + 5 correct DMY texts (day > 12)',
    },
    { header: 'Reported On', primitive: 'date', note: 'CONTROL: clean ISO, no anomaly may be reported' },
    { header: 'Sent To Client', primitive: 'date', dateOrder: 'DMY', note: 'CONTROL: all-text DMY, no serials, no anomaly' },
    { header: 'Fee', primitive: 'money' },
    { header: 'Stage', primitive: 'enum' },
  ],
  aoa: [
    ['Engagement', 'Client', 'Partner', 'Target Date', 'Reported On', 'Sent To Client', 'Fee', 'Stage'],
    ['Statutory audit 2025', 'Halcyon Foods Ltd', 'R. Tounsi', target(0), '2026-01-09', '15/2/2026', 'QAR 42,000', 'Fieldwork'],
    ['Group consolidation review', 'Halcyon Foods Ltd', 'R. Tounsi', target(1), '2026-01-16', '13/2/2026', 'QAR 18,500', 'Fieldwork'],
    ['VAT health check', 'Verdemar Retail', 'N. Farouk', target(2), '2026-01-16', '14/2/2026', 'QAR 9,750', 'Planning'],
    ['Transfer pricing file', 'Cinder Peak Mining', 'N. Farouk', target(3), '2026-01-05', '19/1/2026', 'QAR 27,000', 'Complete'],
    ['Interim review Q4', 'Verdemar Retail', 'R. Tounsi', target(4), '2026-01-23', '16/2/2026', 'QAR 12,400', 'Fieldwork'],
    ['Payroll compliance audit', 'Ardent Logistics', 'S. Okoro', target(5), '2026-02-02', '26/2/2026', 'QAR 15,900', 'Planning'],
    ['Fixed asset verification', 'Cinder Peak Mining', 'S. Okoro', target(6), '2026-02-09', '27/2/2026', 'QAR 8,200', 'Planning'],
    ['Inventory count attendance', 'Ardent Logistics', 'N. Farouk', target(7), '2026-02-16', '14/3/2026', 'QAR 6,400', 'Fieldwork'],
    ['Going concern memo', 'Halcyon Foods Ltd', 'R. Tounsi', target(8), '2026-02-20', '13/3/2026', 'QAR 4,800', 'Review'],
    ['Related party mapping', 'Verdemar Retail', 'S. Okoro', target(9), '2026-03-02', '20/3/2026', 'QAR 7,300', 'Review'],
    ['Deferred tax recompute', 'Cinder Peak Mining', 'N. Farouk', target(10), '2026-03-09', '15/4/2026', 'QAR 11,100', 'Planning'],
    ['Board reporting pack', 'Ardent Logistics', 'R. Tounsi', target(11), '2026-03-16', '18/4/2026', 'QAR 5,600', 'Planning'],
  ],
};

// ─── M2. Tool wreckage — formula errors, null vocabulary, text/number swaps ──

const TOOL_WRECKAGE: WorkbookSpec = {
  id: 'messy-errors-and-nulls',
  industry: 'Procurement — RFQ log exported out of a broken workbook',
  headerRow: 0,
  nameColumn: 1,
  notes:
    'The export ran with broken formulas still in the sheet. Error values are the SOURCE TOOL failing, ' +
    'not data, and importing "#REF!" as a fee or a project name is the silent-corruption shape. Also: a ' +
    'column that is 100% null vocabulary, quantities stored as text, and part codes stored as numbers ' +
    '(so their leading zeros are already gone before we see them — nothing can recover those).',
  columns: [
    { header: 'RFQ', primitive: 'unique_id' },
    { header: 'Vendor', primitive: 'unique_id', note: 'THE entity name' },
    {
      header: 'Quoted', primitive: 'money', anomalies: ['formula_error'],
      note: '2 cells are #DIV/0! — a broken unit-price formula',
    },
    {
      header: 'Due', primitive: 'date', anomalies: ['formula_error'],
      note: '2 cells are #N/A from a failed lookup',
    },
    {
      header: 'Buyer Email', primitive: 'email', anomalies: ['formula_error'],
      note: '1 cell is #REF! — the source column was deleted',
    },
    {
      header: 'Site Visit', primitive: 'empty',
      note: 'EVERY cell is null vocabulary: N/A, n/a, -, --, TBD, ?, none, NULL. The column holds nothing.',
    },
    { header: 'Qty', primitive: 'money', note: 'quantities stored as TEXT, thousands separators included' },
    { header: 'Part Code', primitive: 'unique_id', note: 'codes stored as NUMBERS' },
    { header: 'Status', primitive: 'enum', note: 'a real vocabulary with null placeholders mixed in' },
    { header: 'Ref Tag', primitive: 'unique_id', note: "leading-apostrophe text escapes, as a CSV export leaves them" },
  ],
  aoa: [
    ['RFQ', 'Vendor', 'Quoted', 'Due', 'Buyer Email', 'Site Visit', 'Qty', 'Part Code', 'Status', 'Ref Tag'],
    ['RFQ-2026-001', 'Redhawk Earthworks', '18,400.00', '2026-02-10', 'p.andrade@example.com', 'N/A', '250', 7734, 'Awarded', "'0088-A"],
    ['RFQ-2026-002', 'Ironvale Steel', '#DIV/0!', '2026-02-14', 'p.andrade@example.com', 'n/a', '1,000', 8812, 'Awarded', "'0091-A"],
    ['RFQ-2026-003', 'Clearline Facade', '9,250.00', '#N/A', 'l.venn@example.com', '-', '75', 9014, 'Open', "'0104-B"],
    ['RFQ-2026-004', 'Summit Ridge Roofing', '31,900.00', '2026-02-27', '#REF!', '--', '1,480', 9377, 'Open', "'0112-B"],
    ['RFQ-2026-005', 'Harborline Mechanical', '#DIV/0!', '2026-03-04', 'l.venn@example.com', 'TBD', '620', 10402, 'Declined', "'0118-C"],
    ['RFQ-2026-006', 'Voltaic Power Systems', '44,100.00', '#N/A', 'd.mbeki@example.com', '?', '2,300', 11065, 'Open', "'0125-C"],
    ['RFQ-2026-007', 'Redline Suppression', '7,600.00', '2026-03-18', 'd.mbeki@example.com', 'none', '90', 11810, 'Awarded', "'0133-D"],
    ['RFQ-2026-008', 'Bluestone Concrete', '52,750.00', '2026-03-25', 'p.andrade@example.com', 'NULL', '3,150', 12294, 'Open', "'0140-D"],
    ['RFQ-2026-009', 'Meridian Interiors', '13,300.00', '2026-04-01', 'l.venn@example.com', 'N/A', '410', 12871, 'Declined', "'0147-E"],
    ['RFQ-2026-010', 'Anselm Ceramics', '21,050.00', '2026-04-08', 'd.mbeki@example.com', 'n/a', '860', 13330, 'Awarded', "'0155-E"],
  ],
};

// ─── M3. Within-column format mixing (plan §21.3 C) ─────────────────────────

const FORMAT_SOUP: WorkbookSpec = {
  id: 'messy-format-soup',
  industry: 'Facilities — maintenance jobs typed by four different people',
  headerRow: 0,
  nameColumn: 0,
  notes:
    'No two people entering this sheet agreed on a format. One date column carries ISO, d/m/y and prose ' +
    'together; the fee column carries four money dialects; the sign-off column says yes in three ' +
    'vocabularies; and one column was quietly repurposed halfway down the file.',
  columns: [
    { header: 'Job', primitive: 'unique_id', note: 'THE entity name' },
    { header: 'Building', primitive: 'enum' },
    {
      header: 'Deadline', primitive: 'date', dateOrder: 'DMY',
      note: 'ISO + d/m/y + prose in ONE column — partial coverage is the correct answer, not a failure',
    },
    { header: 'Cost', primitive: 'money', note: 'QAR 4,500 / 4500 / 4,500.00 / EUR 3.200,50 / 2.4k' },
    {
      header: 'Signed Off', primitive: 'enum', anomalies: ['mixed_boolean_dialect'],
      note: 'Y/N and TRUE/FALSE and 1/0 in the same column — one flag, three vocabularies',
    },
    {
      header: 'Assigned', primitive: 'date', alsoOk: ['freetext', 'enum', 'unknown'],
      anomalies: ['meaning_change'],
      note: 'MEANING CHANGES: the top half holds the date assigned, the bottom half holds who it was assigned TO',
    },
    { header: 'Priority', primitive: 'enum' },
    { header: 'Notes', primitive: 'freetext', note: 'one cell carries three separate facts' },
  ],
  aoa: [
    ['Job', 'Building', 'Deadline', 'Cost', 'Signed Off', 'Assigned', 'Priority', 'Notes'],
    ['Chiller 3 overhaul', 'Tower A', '2026-02-11', 'QAR 4,500', 'Y', '2026-01-04', 'High', 'Contact: Dana ext 4120; PO 44120; parts on 3wk lead'],
    ['Lift 2 annual inspection', 'Tower A', '18/2/2026', '3200', 'Y', '2026-01-06', 'Med', ''],
    ['Fire panel recommission', 'Tower B', '2026-02-20', 'QAR 12,750', 'TRUE', '2026-01-09', 'High', 'Needs civil defence witness; booked'],
    ['Roof membrane patch', 'Tower B', 'after Ramadan', '2,400.00', 'N', '2026-01-13', 'Low', 'Deferred once already'],
    ['Generator load bank test', 'Podium', '3/3/2026', 'EUR 3.200,50', 'FALSE', '2026-01-15', 'Med', 'Vendor quote in EUR'],
    ['BMS sensor recalibration', 'Podium', '2026-03-09', '1.8k', '1', '2026-01-20', 'Low', ''],
    ['Water tank chlorination', 'Tower A', '21/3/2026', 'QAR 6,100', '0', 'M. Sadiq', 'Med', 'Lab report to follow; cert expires Sep'],
    ['Car park line marking', 'Basement', 'when access allows', '980', 'Y', 'K. Fahmy', 'Low', ''],
    ['Duct cleaning floors 1-8', 'Tower B', '2026-04-02', 'QAR 22,400', 'TRUE', 'M. Sadiq', 'High', 'Night works only'],
    ['Facade anchor load test', 'Tower B', '14/4/2026', '5,600.00', '1', 'R. Bassiouni', 'Med', 'Third party cert required; 2 anchors failed last time'],
    ['Pump room valve swap', 'Basement', '2026-04-16', '2.4k', 'N', 'K. Fahmy', 'Low', ''],
    ['Emergency lighting sweep', 'Podium', '27/4/2026', 'QAR 3,050', 'FALSE', 'R. Bassiouni', 'Med', 'Batch 2 of 3'],
  ],
};

// ─── M4. Entity naming drift inside ONE file (plan §21.3 B) ─────────────────

const ENTITY_DRIFT: WorkbookSpec = {
  id: 'messy-entity-drift',
  industry: 'Audit firm — engagement list keyed by hand-typed client names',
  headerRow: 0,
  nameColumn: 1,
  notes:
    'Three clients, each typed four ways across twelve rows: case drift, a trailing space, a trailing ' +
    'full stop, and the dotted legal-suffix dialect (L.L.C. / W.L.L.). Nothing in the parser looked ' +
    'INSIDE a file for this before §21 — normalizeClientName only ever compared an incoming name with ' +
    'clients that already existed, so twelve rows produced twelve clients.',
  columns: [
    {
      header: 'Client', primitive: 'unique_id', alsoOk: ['freetext'],
      anomalies: ['entity_variants'],
      note: 'THE TRAP: 3 real clients wearing 12 spellings, so the column looks perfectly unique',
    },
    {
      header: 'Engagement', primitive: 'freetext',
      note: 'THE entity name — and it REPEATS: three clients each get a "Statutory audit 2025"',
    },
    {
      header: 'Partner', primitive: 'enum', anomalies: ['entity_variants'],
      note: 'the same two people with case drift — §18.3\'s "Abdallah kamel" case',
    },
    { header: 'Fee', primitive: 'money' },
    { header: 'Start', primitive: 'date', note: 'clean ISO' },
    { header: 'Status', primitive: 'enum', note: 'CONTROL: a clean vocabulary, no drift to report' },
  ],
  aoa: [
    ['Client', 'Engagement', 'Partner', 'Fee', 'Start', 'Status'],
    ['Acme LLC', 'Statutory audit 2025', 'Y. Haddad', 'QAR 38,000', '2026-01-05', 'Open'],
    ['ACME L.L.C.', 'Interim review H1', 'Y. Haddad', 'QAR 14,500', '2026-01-12', 'Open'],
    ['Acme  LLC ', 'Tax computation 2025', 'F. Nasrallah', 'QAR 9,200', '2026-01-19', 'Closed'],
    ['Acme LLC.', 'Payroll compliance check', 'Y. haddad', 'QAR 6,800', '2026-01-26', 'Open'],
    ['Borealis Trading W.L.L.', 'Statutory audit 2025', 'F. Nasrallah', 'QAR 44,000', '2026-02-02', 'Open'],
    ['Borealis Trading WLL', 'Group consolidation', 'F. nasrallah', 'QAR 21,300', '2026-02-09', 'Open'],
    ['borealis trading w.l.l.', 'VAT return review', 'Y. Haddad', 'QAR 7,400', '2026-02-16', 'Closed'],
    ['Borealis Trading W.L.L', 'Fixed asset register', 'F. Nasrallah', 'QAR 5,900', '2026-02-23', 'Open'],
    ['Cedarpoint Holding', 'Statutory audit 2025', 'Y. Haddad', 'QAR 51,000', '2026-03-02', 'Open'],
    ['CedarPoint Holding', 'Transfer pricing file', 'F. Nasrallah', 'QAR 33,600', '2026-03-09', 'Open'],
    ['Cedarpoint  Holding', 'Going concern memo', 'Y. Haddad', 'QAR 4,100', '2026-03-16', 'Closed'],
    ['Cedarpoint Holding.', 'Board reporting pack', 'F. Nasrallah', 'QAR 8,700', '2026-03-23', 'Open'],
  ],
};

// ─── M5. Structural mess (plan §21.3 D) ────────────────────────────────────

const STRUCTURE: WorkbookSpec = {
  id: 'messy-structure',
  industry: 'Events — supplier bookings, two tables pasted into one sheet',
  headerRow: 0,
  nameColumn: 0,
  notes:
    'Someone pasted the Q2 table under the Q1 table, header row and all, put a section title between ' +
    'them, and duplicated two rows in the process. Every one of those imports as a project unless it is ' +
    'surfaced. The Notes column holds three facts per cell, which is fine — it just must not be dropped.',
  columns: [
    {
      header: 'Supplier', primitive: 'freetext',
      note: 'THE entity name — repeats, because a supplier is booked for more than one event',
    },
    { header: 'Service', primitive: 'enum', note: '7 categories over 10 rows — just misses the enum ratio (§18.7 #15)' },
    { header: 'Event Date', primitive: 'date', note: 'clean ISO' },
    { header: 'Fee', primitive: 'money' },
    { header: 'Owner', primitive: 'enum' },
    { header: 'Notes', primitive: 'freetext', note: 'several facts per cell — carried, never parsed' },
  ],
  rowTraps: [
    { marker: 'Q2 BOOKINGS', kind: 'section', note: 'a section title mid-table, alone in the name column' },
    { marker: 'Supplier', kind: 'header_repeat', note: 'the header row pasted again — the second table starts here' },
    { marker: 'Northgate Catering', kind: 'duplicate', note: 'pasted twice; must be flagged, never silently deduped' },
  ],
  blankRows: 1,
  aoa: [
    ['Supplier', 'Service', 'Event Date', 'Fee', 'Owner', 'Notes'],
    ['Northgate Catering', 'Catering', '2026-02-14', 'QAR 18,400', 'L. Achour', 'Halal cert on file; 180 pax; invoice net 30'],
    ['Lumen Stage Systems', 'AV', '2026-02-14', 'QAR 26,900', 'L. Achour', 'Rig from 06:00; 2 techs on site'],
    ['Northgate Catering', 'Catering', '2026-02-14', 'QAR 18,400', 'L. Achour', 'Halal cert on file; 180 pax; invoice net 30'],
    ['Palmwood Furnishings', 'Furniture', '2026-02-28', 'QAR 9,300', 'K. Sarraf', 'Delivery window 14:00-16:00'],
    ['Zephyr Transport', 'Logistics', '2026-03-07', 'QAR 12,150', 'K. Sarraf', '3 vans; driver contact on the day'],
    [null, null, null, null, null, null],
    ['Q2 BOOKINGS', '', '', '', '', ''],
    ['Supplier', 'Service', 'Event Date', 'Fee', 'Owner', 'Notes'],
    ['Cobalt Print House', 'Print', '2026-04-11', 'QAR 4,750', 'L. Achour', 'Artwork due 10 days prior'],
    ['Lumen Stage Systems', 'AV', '2026-04-25', 'QAR 31,200', 'K. Sarraf', 'Same rig as Feb; add 4 movers'],
    ['Silverbrook Security', 'Security', '2026-05-09', 'QAR 7,800', 'L. Achour', '6 guards; SIA numbers with HR'],
    ['Palmwood Furnishings', 'Furniture', '2026-05-23', 'QAR 11,600', 'K. Sarraf', 'Second hall only'],
    ['Marisol Florals', 'Florals', '2026-06-06', 'QAR 3,400', 'L. Achour', 'Seasonal substitution allowed'],
  ],
};

export const CORPUS_MESSY: WorkbookSpec[] = [
  MDY_ROUNDTRIP,
  TOOL_WRECKAGE,
  FORMAT_SOUP,
  ENTITY_DRIFT,
  STRUCTURE,
];
