-- ====================================================================
-- Issue #191 Phase 10 — PROJECT-LEVEL NOTIFICATIONS
--
-- Projects already emit exactly ONE event: project.stage_transition
-- (20260803_project_stage_engine.sql).  Everything else about a project
-- is silent.  This file adds the remaining four:
--
--   2. project.flag_raised     — a project is flagged blocked / at_risk /
--                                awaiting_client
--   3. project.due_soon        — a project's due_date is approaching
--   4. portfolio.completed     — every project in a portfolio reached a
--                                success-terminal stage
--   5. project_template.updated— a project template's contents changed
--
-- (1., project stage moves, already shipped.  Nothing here touches it.)
--
-- MECHANISM — mirrored, not invented.  This app has exactly one
-- notification pathway:
--
--   fn_emit_notification_event(type, entity_type, entity_id, actor, payload)
--       -> INSERT INTO notification_events
--       -> trg_dispatch_notification_event (pg_net)
--       -> process-notification-event Edge Function
--       -> notification_rules lookup -> recipient strategy -> notify
--
-- Every event below goes through that same entry point.  No second path.
--
-- VISIBILITY — every recipient list is generated by enumerating the
-- company and FILTERING through fn_project_accessible, exactly as
-- fn_project_stage_notify_recipients (20260803) already does.  The
-- predicate is auth.uid()-bound and therefore unreachable from the Edge
-- Function's service-role client, so the database resolves the list at
-- emit time and hands it over in the payload; the Edge Function's
-- `payload_users` strategy consumes it verbatim and must not widen it.
-- That is what makes "we never told someone about a project they cannot
-- open" (issues #185/#186) provable from SQL.
--
-- "DONE" is `is_terminal AND terminal_type = 'success'` everywhere in
-- this file — the same definition fn_project_projection,
-- rpc_projects_table and rpc_portfolios_table use.  Never completed_at.
--
-- RE-RUNNABLE: yes.  Every CREATE is OR REPLACE, every trigger is
-- DROP ... IF EXISTS first, every rule seed is guarded by NOT EXISTS,
-- and the cron job is unscheduled before being scheduled.
-- ====================================================================


-- ────────────────────────────────────────────────────────────────────
-- 0. RECIPIENT RESOLVERS
-- ────────────────────────────────────────────────────────────────────
-- fn_project_stage_notify_recipients(project) already answers "which
-- users in this company can see this project" and is reused as-is by
-- the flag and due-date events below.  Its name says "stage" because
-- that was its first caller; it has never been stage-specific.  It is
-- NOT renamed here: renaming means DROP + re-CREATE + re-GRANT and a
-- patch of fn_trg_projects_notify_stage's live body, all to change a
-- word.  Reuse beats rename.
--
-- Two things it cannot answer, so two siblings:
--   fn_portfolio_notify_recipients  — union across a portfolio
--   fn_template_notify_recipients   — templates aren't projects and
--                                     have no per-row predicate

-- ── Portfolio: anyone who can open AT LEAST ONE project in it ────────
-- Union, not intersection.  The event names only the portfolio, and
-- portfolios_select is already company-wide (company_id = my_company_id),
-- so every user reached here can open the thing the notification is
-- about.  Intersection would be near-always empty and ship nothing.
--
-- ponytail: O(company users) accessibility calls, short-circuited by
-- EXISTS on the first visible project.  It runs once per portfolio, at
-- most once a day (see the dedup in the trigger).  If a large tenant
-- makes it hot, pre-filter the CANDIDATE query wider (owner / has an
-- assignment / holds project.view_all) — never narrower, and never a
-- second copy of the predicate.
CREATE OR REPLACE FUNCTION public.fn_portfolio_notify_recipients(p_portfolio_id uuid)
RETURNS uuid[]
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  -- Saved so the caller's transaction is left exactly as we found it;
  -- set_config(is_local := true) lasts to end of transaction and this
  -- runs inside somebody else's statement.
  v_prev_claims TEXT := current_setting('request.jwt.claims', true);
  v_prev_sub    TEXT := current_setting('request.jwt.claim.sub', true);
  v_projects    uuid[];
  v_candidates  uuid[];
  v_uid         uuid;
  v_pid         uuid;
  v_seen        BOOLEAN;
  v_out         uuid[] := '{}';
BEGIN
  SELECT COALESCE(array_agg(pr.id), '{}')
  INTO   v_projects
  FROM   public.projects pr
  WHERE  pr.portfolio_id = p_portfolio_id
    AND  pr.deleted_at IS NULL;

  IF COALESCE(array_length(v_projects, 1), 0) = 0 THEN
    RETURN '{}';
  END IF;

  SELECT COALESCE(array_agg(u.id), '{}')
  INTO   v_candidates
  FROM   public.users u
  WHERE  u.deleted_at IS NULL
    AND  u.is_active
    AND  u.company_id = (
           SELECT po.company_id FROM public.portfolios po
           WHERE po.id = p_portfolio_id AND po.deleted_at IS NULL
         );

  FOREACH v_uid IN ARRAY v_candidates LOOP
    -- auth.uid() coalesces request.jwt.claim.sub (legacy) with
    -- request.jwt.claims->>'sub'; both have to move or the legacy one
    -- wins and every candidate is evaluated as the real caller.
    PERFORM set_config('request.jwt.claim.sub', v_uid::text, true);
    PERFORM set_config(
      'request.jwt.claims',
      json_build_object('sub', v_uid::text, 'role', 'authenticated')::text,
      true
    );

    v_seen := FALSE;
    FOREACH v_pid IN ARRAY v_projects LOOP
      IF public.fn_project_accessible(v_pid) THEN
        v_seen := TRUE;
        EXIT;
      END IF;
    END LOOP;

    IF v_seen THEN
      v_out := v_out || v_uid;
    END IF;
  END LOOP;

  PERFORM set_config('request.jwt.claim.sub', COALESCE(v_prev_sub, ''), true);
  PERFORM set_config('request.jwt.claims',    COALESCE(v_prev_claims, ''), true);

  RETURN v_out;
END;
$$;


-- ── Template: whoever is allowed to EDIT templates ───────────────────
-- Templates have no per-row visibility predicate — project_templates_select
-- is company-wide.  So "who cares that a template changed" is not a
-- visibility question, it is the same gate rpc_update_project_template
-- itself enforces: is_owner OR project.create.  has_permission() already
-- returns TRUE for every owner, so that one call is the whole gate; a
-- separate is_owner branch here would be a second copy of the rule.
--
-- Same impersonation shape as the two functions above, for the same
-- reason: has_permission() is auth.uid()-bound.
CREATE OR REPLACE FUNCTION public.fn_template_notify_recipients(p_template_id uuid)
RETURNS uuid[]
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_prev_claims TEXT := current_setting('request.jwt.claims', true);
  v_prev_sub    TEXT := current_setting('request.jwt.claim.sub', true);
  v_candidates  uuid[];
  v_uid         uuid;
  v_out         uuid[] := '{}';
BEGIN
  SELECT COALESCE(array_agg(u.id), '{}')
  INTO   v_candidates
  FROM   public.users u
  WHERE  u.deleted_at IS NULL
    AND  u.is_active
    AND  u.company_id = (
           SELECT t.company_id FROM public.project_templates t
           WHERE t.id = p_template_id AND t.deleted_at IS NULL
         );

  FOREACH v_uid IN ARRAY v_candidates LOOP
    PERFORM set_config('request.jwt.claim.sub', v_uid::text, true);
    PERFORM set_config(
      'request.jwt.claims',
      json_build_object('sub', v_uid::text, 'role', 'authenticated')::text,
      true
    );
    IF public.has_permission('project.create') THEN
      v_out := v_out || v_uid;
    END IF;
  END LOOP;

  PERFORM set_config('request.jwt.claim.sub', COALESCE(v_prev_sub, ''), true);
  PERFORM set_config('request.jwt.claims',    COALESCE(v_prev_claims, ''), true);

  RETURN v_out;
END;
$$;


-- ────────────────────────────────────────────────────────────────────
-- 2. FLAGS RAISED  ->  project.flag_raised
-- ────────────────────────────────────────────────────────────────────
-- A project has TWO live representations of "blocked" and this is not
-- an accident this migration gets to clean up: 20260801_project_header_flags
-- deliberately shipped `flags text[]` / `flag_note` ADDITIVELY next to the
-- older `blocked` / `blocked_reason` pair, because both still have real
-- readers and writers (rpc_projects_table + ProjectsTable.tsx read
-- `blocked`; ProjectBlockedToggle.tsx writes it; the #184 header reads
-- and writes `flags`).  Reconciling them is explicitly flagged-not-
-- answered there, and a notification migration is the wrong place to
-- answer it.
--
-- So the event reads the UNION of both, and only fires on flags that
-- were NOT set before.  Whichever surface the user clicked, they get one
-- notification; clicking both surfaces for the same flag gets them one,
-- not two; CLEARING a flag is silent (nobody needs a push saying a
-- problem went away).
CREATE OR REPLACE FUNCTION public.fn_trg_projects_notify_flags()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_old   TEXT[];
  v_new   TEXT[];
  v_added TEXT[];
BEGIN
  -- Same suppression rpc_instantiate_template uses for per-task
  -- notifications: a bulk batch emits one event, not one per row.
  IF current_setting('trustflow.bulk_instantiate', true) = 'on' THEN
    RETURN NEW;
  END IF;

  v_old := COALESCE(OLD.flags, '{}') || CASE WHEN OLD.blocked THEN ARRAY['blocked'] ELSE '{}'::TEXT[] END;
  v_new := COALESCE(NEW.flags, '{}') || CASE WHEN NEW.blocked THEN ARRAY['blocked'] ELSE '{}'::TEXT[] END;

  SELECT COALESCE(array_agg(DISTINCT f), '{}')
  INTO   v_added
  FROM   unnest(v_new) AS f
  WHERE  f <> ALL (v_old);

  IF COALESCE(array_length(v_added, 1), 0) = 0 THEN
    RETURN NEW;   -- flags were cleared or only the note changed
  END IF;

  PERFORM public.fn_emit_notification_event(
    'project.flag_raised',
    'project',
    NEW.id,
    auth.uid(),   -- NULL for system/cron operations
    jsonb_build_object(
      'project_id',         NEW.id,
      'project_name',       NEW.name,
      'pipeline_id',        NEW.pipeline_id,
      'portfolio_id',       NEW.portfolio_id,
      'flags_added',        to_jsonb(v_added),
      -- Whichever surface carries the explanation. flag_note is the
      -- newer one, so it wins when both are populated.
      'reason',             COALESCE(NEW.flag_note, NEW.blocked_reason),
      'recipient_user_ids', to_jsonb(public.fn_project_stage_notify_recipients(NEW.id))
    )
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_projects_notify_flags ON public.projects;
CREATE TRIGGER trg_projects_notify_flags
  AFTER UPDATE OF blocked, blocked_reason, flags, flag_note ON public.projects
  FOR EACH ROW
  WHEN (NEW.deleted_at IS NULL
        AND (NEW.flags   IS DISTINCT FROM OLD.flags
          OR NEW.blocked IS DISTINCT FROM OLD.blocked))
  EXECUTE FUNCTION public.fn_trg_projects_notify_flags();


-- ────────────────────────────────────────────────────────────────────
-- 4. BATCH COMPLETION  ->  portfolio.completed
-- ────────────────────────────────────────────────────────────────────
-- Fires off the SAME transition that already emits project.stage_transition
-- (a separate trigger rather than an extra branch inside
-- fn_trg_projects_notify_stage, so that a bug here can never take the
-- shipped stage notification down with it).
--
-- "All projects done" = every non-deleted, non-archived project in the
-- portfolio sits in a stage with is_terminal AND terminal_type='success'.
-- A project with NO stage at all is NOT done — LEFT JOIN + COALESCE(...,
-- FALSE) makes that explicit rather than letting a NULL vanish.
CREATE OR REPLACE FUNCTION public.fn_trg_portfolio_notify_complete()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_total     INT;
  v_pending   INT;
  v_name      TEXT;
BEGIN
  IF NEW.portfolio_id IS NULL THEN
    RETURN NEW;
  END IF;
  IF current_setting('trustflow.bulk_instantiate', true) = 'on' THEN
    RETURN NEW;
  END IF;

  SELECT COUNT(*),
         COUNT(*) FILTER (
           WHERE NOT COALESCE(ps.is_terminal AND ps.terminal_type = 'success', FALSE)
         )
  INTO   v_total, v_pending
  FROM   public.projects pr
  LEFT JOIN public.pipeline_stages ps ON ps.id = pr.current_stage_id
  WHERE  pr.portfolio_id = NEW.portfolio_id
    AND  pr.deleted_at IS NULL
    AND  pr.status <> 'archived';

  -- An empty portfolio has not "completed".
  IF v_total = 0 OR v_pending > 0 THEN
    RETURN NEW;
  END IF;

  -- ponytail: 24h dedup window, not a completed_at stamp on portfolios.
  -- Reopening one project and re-finishing it the same day is silent;
  -- that is the cheap trade for not adding a column + backfill. Upgrade
  -- path if it ever matters: compare against the newest
  -- project_stage_history row that moved a project OUT of a success
  -- stage, instead of a wall-clock window.
  IF EXISTS (
    SELECT 1 FROM public.notification_events ne
    WHERE  ne.event_type = 'portfolio.completed'
      AND  ne.entity_id  = NEW.portfolio_id
      AND  ne.created_at > now() - INTERVAL '24 hours'
  ) THEN
    RETURN NEW;
  END IF;

  SELECT po.name INTO v_name FROM public.portfolios po WHERE po.id = NEW.portfolio_id;

  PERFORM public.fn_emit_notification_event(
    'portfolio.completed',
    'portfolio',
    NEW.portfolio_id,
    auth.uid(),
    jsonb_build_object(
      'portfolio_id',       NEW.portfolio_id,
      'portfolio_name',     v_name,
      'project_count',      v_total,
      'recipient_user_ids', to_jsonb(public.fn_portfolio_notify_recipients(NEW.portfolio_id))
    )
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_portfolio_notify_complete ON public.projects;
CREATE TRIGGER trg_portfolio_notify_complete
  AFTER UPDATE OF current_stage_id ON public.projects
  FOR EACH ROW
  WHEN (NEW.current_stage_id IS DISTINCT FROM OLD.current_stage_id
        AND NEW.current_stage_id IS NOT NULL
        AND NEW.portfolio_id IS NOT NULL
        AND NEW.deleted_at IS NULL)
  EXECUTE FUNCTION public.fn_trg_portfolio_notify_complete();


-- ────────────────────────────────────────────────────────────────────
-- 5. TEMPLATE CHANGES  ->  project_template.updated
-- ────────────────────────────────────────────────────────────────────
-- Trigger on the TABLE, not inside rpc_update_project_template, for the
-- same reason 20260803's stage notification is on the table: a support
-- UPDATE run by hand is still a change other template editors need to
-- see, and putting it in the RPC means the next writer silently opts out.
--
-- Only content changes count. A pure updated_at bump, or the soft delete
-- (deleted_at going non-NULL), emits nothing — a delete is not an edit,
-- and rpc_delete_project_template is the place to notify about that if
-- anyone ever asks.
--
-- ponytail: no rate-limit window. rpc_update_project_template is an
-- explicit Save, and the Edge Function drops the actor from recipients,
-- so the person doing the editing never notifies themselves. If a second
-- template editor complains about a burst, add a 15-minute dedup here in
-- the same shape as portfolio.completed's.
CREATE OR REPLACE FUNCTION public.fn_trg_project_templates_notify()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.fn_emit_notification_event(
    'project_template.updated',
    'project_template',
    NEW.id,
    auth.uid(),
    jsonb_build_object(
      'template_id',        NEW.id,
      'template_name',      NEW.name,
      'task_count',         jsonb_array_length(COALESCE(NEW.body, '[]'::jsonb)),
      'renamed',            (NEW.name IS DISTINCT FROM OLD.name),
      'body_changed',       (NEW.body IS DISTINCT FROM OLD.body),
      'recipient_user_ids', to_jsonb(public.fn_template_notify_recipients(NEW.id))
    )
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_project_templates_notify ON public.project_templates;
CREATE TRIGGER trg_project_templates_notify
  AFTER UPDATE ON public.project_templates
  FOR EACH ROW
  WHEN (NEW.deleted_at IS NULL
        AND OLD.deleted_at IS NULL
        AND (NEW.name        IS DISTINCT FROM OLD.name
          OR NEW.description IS DISTINCT FROM OLD.description
          OR NEW.color       IS DISTINCT FROM OLD.color
          OR NEW.body        IS DISTINCT FROM OLD.body))
  EXECUTE FUNCTION public.fn_trg_project_templates_notify();


-- ────────────────────────────────────────────────────────────────────
-- 3. DEADLINE APPROACHING  ->  project.due_soon
-- ────────────────────────────────────────────────────────────────────
-- Sweep + pg_cron, mirroring fn_check_overdue_tasks
-- (20260502_notification_engine_phase2.sql) exactly: same de-dup shape
-- (one event per subject per calendar day), same NULL actor, same
-- fn_emit_notification_event call.
--
-- TWO deliberate differences from the task sweep, both stated so the
-- next reader does not "fix" them:
--
--   a) 72 hours, not 24. A task is a day's work and a same-day warning
--      is actionable. A project is weeks of work across several people;
--      a warning that lands the morning it is due is a post-mortem, not
--      a heads-up. Three days is the smallest window in which a project
--      owner can actually reschedule.
--
--   b) A project already sitting in a success-terminal stage is skipped.
--      The task sweep uses `status NOT IN ('completed','cancelled')`;
--      projects have no such status (theirs is active/closed/archived),
--      and the app's definition of a finished project is the stage, not
--      a column. Same predicate fn_project_projection / rpc_projects_table
--      / rpc_portfolios_table use — a notification that disagrees with
--      the screen is worse than no notification.
--
-- Overdue (past the due date) is deliberately NOT emitted here: #191
-- Phase 10 asks for "deadlines approaching". Adding project.overdue is
-- a ~20 line copy of the loop below with the window reversed, if asked.
CREATE OR REPLACE FUNCTION public.fn_check_project_deadlines()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_project RECORD;
BEGIN
  FOR v_project IN
    SELECT pr.id, pr.name, pr.pipeline_id, pr.portfolio_id, pr.due_date
    FROM   public.projects pr
    LEFT JOIN public.pipeline_stages ps ON ps.id = pr.current_stage_id
    WHERE  pr.deleted_at IS NULL
      AND  pr.status = 'active'
      AND  pr.due_date BETWEEN now() AND now() + INTERVAL '72 hours'
      AND  NOT COALESCE(ps.is_terminal AND ps.terminal_type = 'success', FALSE)
      AND  NOT EXISTS (
             SELECT 1 FROM public.notification_events ne
             WHERE  ne.event_type = 'project.due_soon'
               AND  ne.entity_id  = pr.id
               AND  ne.created_at >= CURRENT_DATE::TIMESTAMPTZ
           )
  LOOP
    PERFORM public.fn_emit_notification_event(
      'project.due_soon', 'project', v_project.id, NULL,
      jsonb_build_object(
        'project_id',         v_project.id,
        'project_name',       v_project.name,
        'pipeline_id',        v_project.pipeline_id,
        'portfolio_id',       v_project.portfolio_id,
        'due_at',             v_project.due_date,
        'recipient_user_ids', to_jsonb(public.fn_project_stage_notify_recipients(v_project.id))
      )
    );
  END LOOP;
END;
$$;

-- Same schedule shape as notify-overdue-tasks. Unschedule first so the
-- migration is re-runnable, and guard the whole thing on pg_cron being
-- installed (it is not, in every local stack).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule('notify-project-deadlines')
    WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'notify-project-deadlines');

    PERFORM cron.schedule(
      'notify-project-deadlines',
      '15 8 * * *',   -- 08:15 UTC, 15 min after the task sweep
      $cron$SELECT public.fn_check_project_deadlines()$cron$
    );
  ELSE
    RAISE NOTICE 'pg_cron not installed — fn_check_project_deadlines created but NOT scheduled';
  END IF;
END;
$$;


-- ────────────────────────────────────────────────────────────────────
-- 6. THE RULES
-- ────────────────────────────────────────────────────────────────────
-- Same seed shape as 20260515_notification_fixes.sql and 20260803's
-- 'Project Stage Moved'.
--
-- TENANCY, stated because it is a known open gap and this file makes it
-- four rows bigger: notification_rules has NO company_id and is not
-- tenant-scoped — one global row per event type, readable by every
-- authenticated user on the platform. That gap is NOT deepened here,
-- because all four rules below use `payload_users`, whose entire job is
-- to hand back a list the DATABASE resolved per-tenant at emit time.
-- The rule row carries no tenant data and cannot widen a recipient set;
-- it only names the payload field to read. A rule that resolved
-- recipients itself (`role`, `company_filehub_members`) WOULD need
-- company_id first. See the report accompanying this migration.
DO $$
DECLARE
  v_owner_id UUID;
BEGIN
  SELECT id INTO v_owner_id FROM public.users WHERE is_owner = TRUE LIMIT 1;
  IF v_owner_id IS NULL THEN
    RAISE NOTICE 'no owner user — notification_rules seed skipped (functions and triggers still installed)';
    RETURN;
  END IF;

  INSERT INTO public.notification_rules
    (name, description, event_type, conditions,
     recipient_strategies, recipient_config, is_active, created_by)
  SELECT r.name, r.description, r.event_type, '{}'::JSONB,
         ARRAY['payload_users'],
         '{"payload_field": "recipient_user_ids"}'::JSONB,
         TRUE, v_owner_id
  FROM (VALUES
    ('Project Flagged',
     'Notify everyone who can see a project when it is flagged blocked, at risk, or awaiting client. Recipients are resolved in the database by fn_project_accessible and carried in the event payload.',
     'project.flag_raised'),
    ('Project Due Soon',
     'Notify everyone who can see a project when its due date is within 72 hours. Recipients are resolved in the database by fn_project_accessible and carried in the event payload.',
     'project.due_soon'),
    ('Batch Completed',
     'Notify everyone who can see any project in a portfolio once every project in it has reached a success-terminal stage.',
     'portfolio.completed'),
    ('Project Template Updated',
     'Notify everyone allowed to edit templates when a project template''s contents change.',
     'project_template.updated')
  ) AS r(name, description, event_type)
  WHERE NOT EXISTS (
    SELECT 1 FROM public.notification_rules nr WHERE nr.event_type = r.event_type
  );
END;
$$;


-- ────────────────────────────────────────────────────────────────────
-- 7. GRANTS + OVERLOAD GUARD
-- ────────────────────────────────────────────────────────────────────
-- No DROP FUNCTION happened above (every function here is either brand
-- new or CREATE OR REPLACE with an unchanged signature), so no grant was
-- silently taken away. These are the grants for the new ones.
GRANT EXECUTE ON FUNCTION public.fn_portfolio_notify_recipients(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_template_notify_recipients(uuid)  TO authenticated;

-- CREATE OR REPLACE with a changed argument list ADDS a signature rather
-- than replacing one, and PostgREST answers PGRST203 for the rest of
-- time (20260802_drop_stale_stage_rpc_overloads.sql exists because of
-- exactly that). Fail the migration here instead of finding out in the UI.
DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN
    SELECT p.proname, count(*) AS n
    FROM   pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE  n.nspname = 'public'
      AND  p.proname IN ('fn_portfolio_notify_recipients',
                         'fn_template_notify_recipients',
                         'fn_trg_projects_notify_flags',
                         'fn_trg_portfolio_notify_complete',
                         'fn_trg_project_templates_notify',
                         'fn_check_project_deadlines',
                         'fn_project_stage_notify_recipients')
    GROUP BY p.proname
  LOOP
    IF r.n <> 1 THEN
      RAISE EXCEPTION 'MIGRATION FAILED: % has % signatures, expected exactly 1', r.proname, r.n;
    END IF;
  END LOOP;
END;
$$;
